services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: devdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]

  backend-fastapi:
    build:
      context: ./apps/backend-fastapi
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://devuser:devpass@postgres:5432/devdb
      REDIS_URL: redis://redis:6379
    depends_on:
      - postgres
      - redis
    volumes:
      - ./apps/backend-fastapi:/app
    ports:
      - "8000:8000"

  backend-nest:
    build:
      context: ./apps/backend-nest
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://devuser:devpass@postgres:5432/devdb
      REDIS_URL: redis://redis:6379
      FASTAPI_URL: http://backend-fastapi:8000
    depends_on:
      - backend-fastapi
    volumes:
      - ./apps/backend-nest:/app
      - /app/node_modules
    ports:
      - "3000:3000"

  frontend-vite:
    build:
      context: ./apps/frontend-vite
    restart: unless-stopped
    environment:
      VITE_API_URL: http://localhost/api
    depends_on:
      - backend-nest
      - backend-fastapi
    volumes:
      - ./apps/frontend-vite:/app
      - /app/node_modules
    ports:
      - "5173:5173"

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend-vite
      - backend-nest
      - backend-fastapi

volumes:
  postgres_data:
