services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: devdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]

  backend-fastapi:
    build:
      context: ./apps/backend-fastapi
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"  # host:container
    env_file:
      - ./apps/backend-fastapi/.env    # Container çalışırken ortam değişkenlerini buradan alır
    volumes:
      - ./apps/backend-fastapi:/app

volumes:
  postgres_data: