services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: devdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]

  backend-fastapi:
    build:
      context: ./apps/backend-fastapi
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"  # host:container
    env_file:
      - ./apps/backend-fastapi/.env    # Container çalışırken ortam değişkenlerini buradan alır
    volumes:
      - ./apps/backend-fastapi:/app

  frontend-vite:
    build:
      context: ./apps/frontend-vite
    restart: unless-stopped
    environment:
      VITE_API_URL: http://localhost/api
    volumes:
      - ./apps/frontend-vite:/app
      - /app/node_modules
    ports:
      - "5173:5173"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:8080"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  postgres_data: